<?php

namespace Encore\OrgRbac\TabTable;

use Encore\Admin\Table;
use Encore\OrgRbac\TabTable\Actions\Delete;
use Encore\OrgRbac\TabTable\Actions\Edit;
use Encore\OrgRbac\TabTable\Tools\CreateButton;


class TabTable extends Table
{
    protected $resourceUrl;
    protected $backUrl;
    protected $createHandleParams = [];

    public function setResourceUrl($resourceUrl)
    {
        $this->resourceUrl = $resourceUrl;
    }

    public function getResourceUrl()
    {
        return $this->resourceUrl;
    }

    public function setBackUrl($backUrl)
    {
        $this->backUrl = $backUrl;
    }

    public function getBackUrl()
    {
        return $this->backUrl;
    }

    public function setCreateHandleParams(array $params)
    {
        $this->createHandleParams = $params;
    }

    public function getCreateHandleParams()
    {
        return $this->createHandleParams;
    }

    /**
     * Render create button for table.
     *
     * @return string
     */
    public function renderCreateButton()
    {
        return (new CreateButton($this,$this->createHandleParams))->render();
    }

    public function __toString()
    {
        return $this->render();
    }

    public function render()
    {
        $resourceUrl = $this->resourceUrl;
        $backUrl = $this->backUrl;
        $this->actions(function ($actions) use($resourceUrl,$backUrl) {
            // 去掉删除
            $actions->disableDelete();
            // 去掉编辑
            $actions->disableEdit();
            // 去掉查看
            $actions->disableView();
            $actions->add(new Edit($resourceUrl,$backUrl));
            $actions->add(new Delete($resourceUrl,$backUrl));
        });
        return parent::render(); // TODO: Change the autogenerated stub
    }
}

